#!/bin/sh

set -e

finish_rm_conffile() {
	local CONFFILE="$1"

	if [ -e "$CONFFILE.dpkg-backup" ]; then
		mv -f "$CONFFILE.dpkg-backup" "$CONFFILE.dpkg-bak"
	fi
	if [ -e "$CONFFILE.dpkg-remove" ]; then
		echo "Removing obsolete conffile $CONFFILE ..."
		rm -f "$CONFFILE.dpkg-remove"
	fi
}

case "$1" in
    configure)
        ucf --three-way /usr/share/nfs-common/conffiles/idmapd.conf /etc/idmapd.conf
        ucf --three-way /usr/share/nfs-common/conffiles/nfs-common.default /etc/default/nfs-common

        if ! getent passwd statd >/dev/null; then
            adduser --system --home /var/lib/nfs --no-create-home statd
        fi
        if dpkg --compare-versions "$2" ge 1:1.0.7-10 && dpkg --compare-versions "$2" lt 1:1.0.7-13; then
            usermod --home /var/lib/nfs statd || true
            if [ -d /home/statd ]; then
                rmdir --ignore-fail-on-non-empty /home/statd
            fi
        fi

        # Don't make /var/lib/nfs owned by statd. Only sm and sm.bak need to be
        # accessible by statd or sm-notify after they drop privileges.
        # (CVE-2019-3689)
        if dpkg --compare-versions "$2" lt 1:1.2.8-9ubuntu12.3; then
                chown root:root /var/lib/nfs
        fi
        chown statd: /var/lib/nfs/sm \
            /var/lib/nfs/sm.bak
        if [ -f /var/lib/nfs/state ]; then
            chown statd /var/lib/nfs/state
        fi
        
        if [ "$2" != "" ] || dpkg --compare-versions "$2" lt 1:1.1.0-14; then
            if dpkg-statoverride --list /sbin/mount.nfs >/dev/null 2>&1; then
                dpkg-statoverride --remove /sbin/mount.nfs
            fi
        fi

	if dpkg --compare-versions "$2" lt-nl 1:1.2.0-2ubuntu1
	then
		if [ -e /etc/init.d/nfs-common.dpkg-remove ]
		then
			invoke-rc.d nfs-common.dpkg-remove stop
		elif [ -e /etc/init.d/nfs-common.dpkg-backup ]
		then
			invoke-rc.d nfs-common.dpkg-backup stop
		fi
		update-rc.d nfs-common remove
	elif dpkg --compare-versions "$2" lt-nl 1:1.2.4-1ubuntu3
	then
		# handle the move of rpc_pipefs from /var/lib to /run
		invoke-rc.d idmapd stop
		invoke-rc.d gssd stop
		if [ -d /var/lib/nfs/rpc_pipefs ]; then
			rmdir --ignore-fail-on-non-empty /var/lib/nfs/rpc_pipefs
		fi
	fi

	# Migrate /lib/init/rw/sendsigs.omit.statd to /run.
	if [ -f /lib/init/rw/sendsigs.omit.d/statd ]; then 
	    mv /lib/init/rw/sendsigs.omit.d/statd /run/sendsigs.omit.d/statd
	fi

	# Remove enablement flag in conffile
	DEFAULT_CONFFILE=/etc/default/nfs-common
	if [ -f ${DEFAULT_CONFFILE}.statd.enable ]; then
		# enable upstart and systemd jobs. Ignore errors as name mapping isn't one to one
		# upstart jobs are not disabled under systemd by update-rc.d wihout sysvinit file.
		sed -i 's/manual//' /etc/init/statd-mounting.override 2>/dev/null || true
		if [ `stat -c%s /etc/init/whoopsie.override` -eq 0 ]; then
			rm -f /etc/init/statd-mounting.override /etc/init/statd.override
		fi
		update-rc.d rpc-statd-notify enable >/dev/null 2>&1 || true
		update-rc.d rpc-statd enable >/dev/null 2>&1 || true
		rm -f ${DEFAULT_CONFFILE}.statd.enable
	fi
    ;;
esac

#DEBHELPER#

finish_rm_conffile /etc/init.d/nfs-common
